In [32]:
import numpy
import sys

def ITEMWISE_METRICS(observed, observed_ratings, predicted_ratings,y,w):
    delta = numpy.ma.subtract(predicted_ratings,observed_ratings)
#     rectifiedDelta = numpy.square(delta)
    rectifiedDelta = numpy.ma.abs(delta)
    print("rectifiedDelta")
    print(rectifiedDelta)
    
    numUsers,numItems = numpy.shape(observed_ratings)
    scale = numUsers * numItems
    
    #e^_{u,i} = w(r^_{u,i}-y)^2
#     imputed_error = (numpy.square(numpy.ma.subtract(predicted_ratings,y))) * w 
    imputed_error = (numpy.ma.abs(numpy.ma.subtract(predicted_ratings,y))) * w 
    print("imputed_error")
    print(imputed_error)
    
    #OE1 = o_{u,i}e_{u,i}
    observedError1 = numpy.ma.multiply(observed,rectifiedDelta)
    print("observedError1")
    print(observedError1)
    
    #OE2 = (1-o{u,i})*e^_{u,i}
    unobserved = numpy.ma.subtract(numpy.ones((numUsers,numItems)),observed)
    observedError2 = numpy.ma.multiply(unobserved,imputed_error)
    print("observedError2")
    print(observedError2)
    
    
    totalObservedError = observedError1 + observedError2
    cumulativeError = numpy.ma.sum(totalObservedError,dtype = numpy.longdouble)
    print("cumulativeError")
    print(cumulativeError)
    
    vanillaMetric = cumulativeError / scale
    print("vanillaMetric")
    print(vanillaMetric)
    
    return vanillaMetric

In [33]:
if __name__ == "__main__":
    shape = (2,3)
    true_ratings = [[1,1,5],
                    [1,1,5]]
    
    predicted_ratings = [[3,3,4],
                        [3,3,4]]
    a = numpy.ma.array(true_ratings)
    b = numpy.ma.array(predicted_ratings)
    
   
    print ("[MAIN]\t True ratings:")
    print (a)
    print ("[MAIN]\t Predicted ratings:")
    print (b)
    
    observed = [[1,0,0],
                [0,0,1]]
            
    
    
    y = 4.5
    w = 1
    #observerd_ratings 这里不太确定
    
   
    observed_ratings = numpy.ma.array(a, dtype = numpy.longdouble, copy = True, 
                             fill_value = 0, hard_mask = True)
    print("[MAIN]\t observed_ratings")
    print(observed_ratings)
    ITEMWISE_METRICS(observed, observed_ratings,b,y,w)

[MAIN]	 True ratings:
[[1 1 5]
 [1 1 5]]
[MAIN]	 Predicted ratings:
[[3 3 4]
 [3 3 4]]
[MAIN]	 observed_ratings
[[1. 1. 5.]
 [1. 1. 5.]]
rectifiedDelta
[[2. 2. 1.]
 [2. 2. 1.]]
imputed_error
[[1.5 1.5 0.5]
 [1.5 1.5 0.5]]
observedError1
[[2. 0. 0.]
 [0. 0. 1.]]
observedError2
[[0.  1.5 0.5]
 [1.5 1.5 0. ]]
cumulativeError
8.0
vanillaMetric
1.3333333333333333334
