<a href="https://colab.research.google.com/github/Recommendation-System-Project/Recommendation-system/blob/main/Propensities_Coat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
item_features = np.genfromtxt("data/item_features.ascii", dtype=None)
user_features = np.genfromtxt("data/user_features.ascii", dtype=None)
train = np.genfromtxt("data/train.ascii", dtype=None)
test = np.genfromtxt("data/test.ascii", dtype=None)

In [5]:
print("item feature shape: ", item_features.shape)
print("user feature shape: ", user_features.shape)
print("train shape: ", train.shape)
print("test shape: ", test.shape)

item feature shape:  (300, 33)
user feature shape:  (290, 14)
train shape:  (290, 300)
test shape:  (290, 300)


## Auto encode item features

In [6]:
item_gender = item_features[:,:2]
item_type = item_features[:,2:18]
item_color = item_features[:,18:31]
item_promot = item_features[:,31:]
print("item_gender shape: ", item_gender.shape)
print("item_type shape: ", item_type.shape)
print("item_color shape: ", item_color.shape)
print("item_promot shape: ", item_promot.shape)

item_gender shape:  (300, 2)
item_type shape:  (300, 16)
item_color shape:  (300, 13)
item_promot shape:  (300, 2)


In [7]:
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Dense,Flatten,Reshape

Auto encode item type

In [8]:
# Auto encode item type
X_train = item_type
encode_dim = 10
 
## Encoder
encoder = Sequential()
# encoder.add(Flatten(input_shape=[21,]))
encoder.add(Dense(X_train.shape[1]))
encoder.add(Dense(400,activation="relu"))
encoder.add(Dense(200,activation="relu"))
encoder.add(Dense(100,activation="relu"))
encoder.add(Dense(50,activation="relu"))
encoder.add(Dense(encode_dim,activation="relu"))
 
## Decoder
decoder = Sequential()
decoder.add(Dense(50,input_shape=[encode_dim],activation='relu'))
decoder.add(Dense(100,activation='relu'))
decoder.add(Dense(200,activation='relu'))
decoder.add(Dense(400,activation='relu'))
decoder.add(Dense(X_train.shape[1], activation="relu"))
# decoder.add(Reshape([943, 21]))
 
## Autoencoder
autoencoder = Sequential([encoder,decoder])
autoencoder.compile(loss="mse")
autoencoder.fit(X_train,X_train,epochs=50)
 
encoded_item_type = encoder.predict(X_train)

Epoch 1/50
10/10 [==============================] - 1s 5ms/step - loss: 0.0558
Epoch 2/50
10/10 [==============================] - 0s 5ms/step - loss: 0.0385
Epoch 3/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0255
Epoch 4/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0181
Epoch 5/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0165
Epoch 6/50
10/10 [==============================] - 0s 5ms/step - loss: 0.0160
Epoch 7/50
10/10 [==============================] - 0s 5ms/step - loss: 0.0152
Epoch 8/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0141
Epoch 9/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0150
Epoch 10/50
10/10 [==============================] - 0s 5ms/step - loss: 0.0133
Epoch 11/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0146
Epoch 12/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0137
Epoch 13/50
10/10 [==============================

16 -> 10

In [9]:
encoded_item_type.shape

(300, 10)

Auto encode item_color

In [10]:
# Auto encode item type
X_train = item_color
encode_dim = 7
 
## Encoder
encoder = Sequential()
# encoder.add(Flatten(input_shape=[21,]))
encoder.add(Dense(X_train.shape[1]))
encoder.add(Dense(400,activation="relu"))
encoder.add(Dense(200,activation="relu"))
encoder.add(Dense(100,activation="relu"))
encoder.add(Dense(50,activation="relu"))
encoder.add(Dense(encode_dim,activation="relu"))
 
## Decoder
decoder = Sequential()
decoder.add(Dense(50,input_shape=[encode_dim],activation='relu'))
decoder.add(Dense(100,activation='relu'))
decoder.add(Dense(200,activation='relu'))
decoder.add(Dense(400,activation='relu'))
decoder.add(Dense(X_train.shape[1], activation="relu"))
# decoder.add(Reshape([943, 21]))
 
## Autoencoder
autoencoder = Sequential([encoder,decoder])
autoencoder.compile(loss="mse")
autoencoder.fit(X_train,X_train,epochs=50)
 
encoded_item_color = encoder.predict(X_train)

Epoch 1/50
10/10 [==============================] - 1s 5ms/step - loss: 0.0675
Epoch 2/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0477
Epoch 3/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0340
Epoch 4/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0221
Epoch 5/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0187
Epoch 6/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0184
Epoch 7/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0177
Epoch 8/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0174
Epoch 9/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0175
Epoch 10/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0166
Epoch 11/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0185
Epoch 12/50
10/10 [==============================] - 0s 4ms/step - loss: 0.0166
Epoch 13/50
10/10 [==============================

14 -> 7

In [11]:
encoded_item_color.shape

(300, 7)

## Join item features

In [12]:
item_features_encoded = np.concatenate((item_gender, encoded_item_type),axis = 1)
item_features_encoded = np.concatenate((item_features_encoded, encoded_item_color),axis = 1)
item_features_encoded = np.concatenate((item_features_encoded, item_promot),axis = 1)
item_features_encoded

array([[1.        , 0.        , 0.        , ..., 0.08179402, 1.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 0.60989726, 0.        ,
        1.        ],
       [1.        , 0.        , 0.94742745, ..., 0.08513641, 0.        ,
        1.        ],
       ...,
       [0.        , 1.        , 0.81452298, ..., 0.        , 0.        ,
        1.        ],
       [0.        , 1.        , 0.34518668, ..., 0.        , 0.        ,
        1.        ],
       [0.        , 1.        , 0.81452298, ..., 0.        , 0.        ,
        1.        ]])

33 -> 21

In [13]:
item_features_encoded.shape

(300, 21)

## Joint user-item pair features

Concatenate user and item features into a matrix for all possible user item pairs

In [14]:
O_mask = np.int64(train > 0)
O_mask

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

creat array that contains features of all possible user-item pairs

47 -> 35

In [15]:
features_matrix = []
for u in range(O_mask.shape[0]):
  for i in range(O_mask.shape[1]):
    user_f = user_features[u]
    item_f = item_features_encoded[i]
    observed = np.concatenate((user_f, item_f))
    features_matrix.append(observed)
features_matrix = np.array(features_matrix)
features_matrix.shape

(87000, 35)

In [27]:
np.savetxt("item_features_encoded.ascii", item_features_encoded, delimiter=" ")

## Log Reg to predict propensity based on features

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
x = features_matrix
y = np.ndarray.flatten(O_mask)

In [18]:
x.shape

(87000, 35)

In [19]:
model = LogisticRegression(max_iter=1000).fit(x,y)
model.classes_, model.intercept_, model.coef_

(array([0, 1]),
 array([-1.8465561]),
 array([[-0.04114871, -0.0411864 , -0.01362282, -0.01360624, -0.01367843,
         -0.01344072, -0.01348495, -0.01450196, -0.02744427, -0.02744846,
         -0.02744238, -0.02742899, -0.02753746, -0.02736866,  0.06899516,
         -0.15133027, -0.10253641,  0.32121909,  0.16257757,  0.        ,
          0.02297736, -0.14141538,  0.09101257,  0.11097323, -0.23474926,
         -0.12614708,  0.5278056 ,  0.08573019,  0.06853603,  0.01738186,
         -0.13175852,  2.86689279,  0.05013738,  0.60198564, -0.68432075]]))

In [20]:
predicted_propensity = model.predict_proba(x)
predicted_propensity

array([[0.72524291, 0.27475709],
       [0.92748207, 0.07251793],
       [0.92952659, 0.07047341],
       ...,
       [0.92118349, 0.07881651],
       [0.91818598, 0.08181402],
       [0.93256819, 0.06743181]])

In [21]:
predicted_propensity = predicted_propensity[:,1].reshape(290, 300)
predicted_propensity

array([[0.27475709, 0.07251793, 0.07047341, ..., 0.07882263, 0.08182036,
        0.06743711],
       [0.27474716, 0.07251458, 0.07047014, ..., 0.07881902, 0.08181661,
        0.06743398],
       [0.27474386, 0.07251347, 0.07046906, ..., 0.07881781, 0.08181537,
        0.06743294],
       ...,
       [0.27475258, 0.07251641, 0.07047192, ..., 0.07882099, 0.08181865,
        0.06743569],
       [0.27474028, 0.07251226, 0.07046788, ..., 0.07881651, 0.08181402,
        0.06743181],
       [0.27474028, 0.07251226, 0.07046788, ..., 0.07881651, 0.08181402,
        0.06743181]])

In [22]:
model.score(x, y)

0.92

In [23]:
np.savetxt("our_propensities.ascii", predicted_propensity, delimiter=" ")

In [24]:
np.genfromtxt("our_propensities.ascii", dtype=None).shape

(290, 300)